version: "3"

services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      gvq-api:
        aliases:
          - mysql.gvq-api.test
    ports:
      - 33066:3306

  web:
    image: 2dotstwice/nginx-php72-symfony4-dev
    environment:
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}
    volumes:
      - .:/usr/share/nginx/html:cached
    networks:
      gvq-api:
        aliases:
          - gvq-api.test
    ports:
      - 8000:80

  mailhog:
    image: mailhog/mailhog
    networks:
      gvq-api:
        aliases:
          - mailhog.gvq-api.test
    ports:
      - 8025:8025
      - 1025:1025

  redis:
    image: redis:alpine
    networks:
      gvq-api:
        aliases:
          - redis.gvq-api.test
    ports:
      - 63799:6379

networks:
  gvq-api:
    driver: bridge
