question_create:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::create
  methods: [POST]
question_get_all:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::getAll
  methods: [GET]
question_get_by_id:
  path: /questions/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::getById
  methods: [GET]
