#
# VIEWS
#
accounts_view_index:
  path: /
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::index
accounts_inschrijven:
  path: /{_locale}/inschrijven
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::register
  methods: [GET, POST]
  requirements:
    _locale: nl
accounts_inscription:
  path: /{_locale}/inscription
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::register
  methods: [GET, POST]
  requirements:
    _locale: fr
accounts_view_register:
  path: /{_locale}/view/accounts/register
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::register
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
accounts_info:
  path: /{_locale}/info
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::info
  methods: [GET]
  requirements:
    _locale: nl|fr
accounts_view_info:
  path: /{_locale}/view/accounts/info
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::info
  methods: [GET]
  requirements:
    _locale: nl|fr
accounts_view_register_success:
  path: /{_locale}/view/accounts/register/success
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::registerSuccess
  methods: [GET]
  requirements:
    _locale: nl|fr
accounts_view_login:
  path: /{_locale}/view/accounts/login
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::login
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
accounts_logout:
  path: /logout
accounts_view_activate:
  path: /{_locale}/view/accounts/activate/{urlSuffix}
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::activate
  methods: [GET]
  requirements:
    _locale: nl|fr
    urlSuffix: "[^/]{44}"
accounts_view_request_password:
  path: /{_locale}/view/accounts/password/request
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::requestPassword
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
accounts_view_request_password_success:
  path: /{_locale}/view/accounts/password/request/success
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::requestPasswordSuccess
  methods: [GET]
  requirements:
    _locale: nl|fr
accounts_view_reset_password:
  path: /{_locale}/view/accounts/password/reset/{urlSuffix}
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::resetPassword
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
    urlSuffix: "[^/]{44}"
accounts_view_reset_password_success:
  path: /{_locale}/view/accounts/password/reset/success
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::resetPasswordSuccess
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
accounts_view_edit_password:
  path: /{_locale}/view/accounts/password/edit
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::editPassword
  methods: [GET, POST]
  requirements:
    _locale: nl|fr

questions_view_index:
  path: /{_locale}/view/questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::index
  methods: [GET]
  requirements:
    _locale: nl|fr
questions_view_print:
  path: /{_locale}/view/questions/print
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::print
  methods: [GET]
  requirements:
    _locale: nl|fr
questions_view_add:
  path: /{_locale}/view/questions/add
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::add
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
questions_view_edit:
  path: /{_locale}/view/questions/edit/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::edit
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
questions_view_edit_image:
  path: /{_locale}/view/questions/image/edit/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::editImage
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
questions_view_delete:
  path: /{_locale}/view/questions/delete/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::delete
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
questions_view_archive:
  path: /{_locale}/view/questions/archive/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::archive
  methods: [GET, POST]
  requirements:
    _locale: nl|fr


companies_view_index:
  path: /{_locale}/view/companies
  controller: VSV\GVQ_API\Company\Controllers\CompanyViewController::index
  methods: [GET]
  requirements:
    _locale: nl|fr
companies_view_add:
  path: /{_locale}/view/companies/add
  controller: VSV\GVQ_API\Company\Controllers\CompanyViewController::add
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
companies_view_edit:
  path: /{_locale}/view/companies/edit/{id}
  controller: VSV\GVQ_API\Company\Controllers\CompanyViewController::edit
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
companies_export:
  path: /{_locale}/csv/companies
  controller: VSV\GVQ_API\Company\Controllers\CompanyViewController::export
  methods: [GET]
  requirements:
    _locale: nl|fr

users_view_index:
  path: /{_locale}/view/users
  controller: VSV\GVQ_API\User\Controllers\UserViewController::index
  methods: [GET]
  requirements:
    _locale: nl|fr
users_view_edit:
  path: /{_locale}/view/users/edit/{id}
  controller: VSV\GVQ_API\User\Controllers\UserViewController::edit
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
users_view_send_activation:
  path: /{_locale}/view/users/activation/send/{id}
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::sendActivation
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
users_export:
  path: /{_locale}/csv/users
  controller: VSV\GVQ_API\User\Controllers\UserViewController::export
  methods: [GET]
  requirements:
    _locale: nl|fr

dashboard:
  path: /{_locale}/view/dashboard/{companyId}
  controller: VSV\GVQ_API\Dashboard\Controllers\DashboardViewController::dashboard
  methods: [GET]
  defaults: { companyId: null }
  requirements:
    _locale: nl|fr
dashboard_export_topscores:
  path: /{_locale}/csv/topscores/{companyId}
  controller: VSV\GVQ_API\Dashboard\Controllers\DashboardViewController::export
  methods: [GET]
  requirements:
    _locale: nl|fr

statistics:
  path: /{_locale}/view/statistics
  controller: VSV\GVQ_API\Statistics\Controllers\StatisticsViewController::statistics
  methods: [GET]
  requirements:
    _locale: nl|fr

report:
  path: /{_locale}/view/report
  controller: VSV\GVQ_API\Report\Controllers\ReportViewController::report
  methods: [GET]
  requirements:
    _locale: nl|fr

documents:
  path: /{_locale}/view/documents
  controller: VSV\GVQ_API\Document\Controllers\DocumentViewController::documents
  methods: [GET]
  requirements:
    _locale: nl|fr

documents_kickoff:
  path: /documents/{document}
  methods: [GET]

privacy_pdf_nl:
  path: /documents/privacy_policy-nl.pdf
privacy_pdf_fr:
  path: /documents/privacy_policy-fr.pdf

contacts_view_edit:
  path: /{_locale}/view/contacts/edit/{id}
  controller: VSV\GVQ_API\User\Controllers\UserViewController::editContact
  methods: [GET, POST]
  defaults: { id: null }
  requirements:
    _locale: nl|fr
quiz:
  path: /quiz
  controller: VSV\GVQ_API\Quiz\Controllers\QuizViewController::showQuiz
  methods: [GET]

quiz_example:
  path: /quiz/example
  controller: VSV\GVQ_API\Quiz\Controllers\QuizExampleController::showQuiz
  methods: [GET, POST]

contest:
  path: /{_locale}/view/contest/{quizId}
  controller: VSV\GVQ_API\Contest\Controllers\ContestViewController::contest
  methods: [GET, POST]

#
# API
#
quiz_start:
  path: /api/quiz
  controller: VSV\GVQ_API\Quiz\Controllers\QuizController::start
  methods: [POST]
quiz_ask_question:
  path: /api/quiz/{quizId}/question
  controller: VSV\GVQ_API\Quiz\Controllers\QuizController::askQuestion
  methods: [GET]
quiz_answer_question:
  path: /api/quiz/{quizId}/question/{answerId}
  controller: VSV\GVQ_API\Quiz\Controllers\QuizController::answerQuestion
  methods: [POST]
