#
# API
#

categories_get_all:
  path: /categories
  controller: VSV\GVQ_API\Question\Controllers\CategoryController::getAll
  methods: [GET]

questions_save:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::save
  methods: [POST]
questions_delete:
  path: /questions/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::delete
  methods: [DELETE]
questions_get_all:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::getAll
  methods: [GET]

companies_save:
  path: /companies
  controller: VSV\GVQ_API\Company\Controllers\CompanyController::save
  methods: [POST]

images_upload:
  path: /images
  controller: VSV\GVQ_API\Image\Controllers\ImageController::upload
  methods: [POST]

account_register:
  path: account/register
  controller: VSV\GVQ_API\Account\Controllers\AccountController::register
  methods: [POST]
account_login:
  path: account/login
  controller: VSV\GVQ_API\Account\Controllers\AccountController::login
  methods: [POST]

#
# VIEWS
#

account_view_register:
  path: /{_locale}/view/accounts/register
  controller: VSV\GVQ_API\Account\Controllers\AccountViewController::register
  methods: [GET, POST]
  requirements:
    _locale: nl|fr

questions_view_index:
  path: /{_locale}/view/questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::index
  methods: [GET]
  requirements:
    _locale: nl|fr
questions_view_add:
  path: /{_locale}/view/questions/add
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::add
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
questions_view_edit:
  path: /{_locale}/view/questions/edit/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::edit
  methods: [GET, POST]
  requirements:
    _locale: nl|fr
questions_view_delete:
  path: /{_locale}/view/questions/delete/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::delete
  methods: [GET, POST]
  requirements:
    _locale: nl|fr

companies_view_index:
  path: /{_locale}/view/companies
  controller: VSV\GVQ_API\Company\Controllers\CompanyViewController::index
  methods: [GET]
  requirements:
    _locale: nl|fr

users_view_index:
  path: /{_locale}/view/users
  controller: VSV\GVQ_API\User\Controllers\UserViewController::index
  methods: [GET]
  requirements:
    _locale: nl|fr
