categories_get_all:
  path: /categories
  controller: VSV\GVQ_API\Question\Controllers\CategoryController::getAll
  methods: [GET]

questions_save:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::save
  methods: [POST]
questions_delete:
  path: /questions/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::delete
  methods: [DELETE]
questions_get_all:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::getAll
  methods: [GET]

images_upload:
  path: /images
  controller: VSV\GVQ_API\Image\Controllers\ImageController::upload
  methods: [POST]

user_login:
  path: /login
  controller: VSV\GVQ_API\User\Controllers\UserAccountController::login
  methods: [POST]
user_register:
  path: /register
  controller: VSV\GVQ_API\User\Controllers\UserAccountController::register
  methods: [POST]
