categories_get_all:
  path: /categories
  controller: VSV\GVQ_API\Question\Controllers\CategoryController::getAll
  methods: [GET]

questions_save:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::save
  methods: [POST]
questions_delete:
  path: /questions/{id}
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::delete
  methods: [DELETE]
questions_get_all:
  path: /questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionController::getAll
  methods: [GET]

companies_save:
  path: /companies
  controller: VSV\GVQ_API\Company\Controllers\CompanyController::save
  methods: [POST]

images_upload:
  path: /images
  controller: VSV\GVQ_API\Image\Controllers\ImageController::upload
  methods: [POST]

account_register:
  path: account/register
  controller: VSV\GVQ_API\Account\Controllers\AccountController::register
  methods: [POST]
account_login:
  path: account/login
  controller: VSV\GVQ_API\Account\Controllers\AccountController::login
  methods: [POST]

questions_index:
  path: view/questions
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::index
  methods: [GET]
questions_add:
  path: view/questions/add
  controller: VSV\GVQ_API\Question\Controllers\QuestionViewController::add
  methods: [GET, POST]

companies_index:
  path: view/companies
  controller: VSV\GVQ_API\Company\Controllers\CompanyViewController::index
  methods: [GET]

users_index:
  path: view/users
  controller: VSV\GVQ_API\User\Controllers\UserViewController::index
  methods: [GET]
