# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'nl'
    sender_email_nl: 'quiz@vsv.be'
    sender_name_nl: 'Grote verkeersquiz 2018'
    sender_email_fr: 'quiz@awsr.be'
    sender_name_fr: 'Quiz de la Route 2018'
    bucket_name: '%env(BUCKET_NAME)%'
    upload_target: '%env(UPLOAD_TARGET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    VSV\GVQ_API\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ### SERVICES ###
    company_json_enricher:
      class: VSV\GVQ_API\Company\Serializers\CompanyJsonEnricher
      arguments:
        $uuidFactory: '@uuid_factory'

    question_json_enricher:
      class: VSV\GVQ_API\Question\Serializers\QuestionJsonEnricher
      arguments:
        $uuidFactory: '@uuid_factory'

    registration_json_enricher:
      class: VSV\GVQ_API\Account\Serializers\RegistrationJsonEnricher
      arguments:
        $uuidFactory: '@uuid_factory'

    local_adapter:
      class: League\Flysystem\Adapter\Local
      arguments:
        $root: '%kernel.project_dir%/public/uploads'

    s3_client:
      class: AWS\S3\S3Client
      factory: Aws\S3\S3Client::factory
      arguments:
        -
          version: 'latest'
          region: 'eu-west-1'

    s3_adapter:
      class: League\Flysystem\AwsS3v3\AwsS3Adapter
      arguments:
        $client: '@s3_client'
        $bucket: '%bucket_name%'

    fly_system:
      class: League\Flysystem\Filesystem
      arguments: ["@=parameter('upload_target')==='remote' ? service('s3_adapter'): service('local_adapter')"]

    image_validator:
      class: VSV\GVQ_API\Image\Validation\ImageValidator
      arguments:
        $maxFileSize: 2097152
        $supportedMimeTypes: ['image/jpeg', 'image/png']

    uuid_factory:
      class: Ramsey\Uuid\UuidFactory

    time_zone:
      class: \DateTimeZone
      arguments:
        - 'Europe/Brussels'

    quiz_delay:
      class: VSV\GVQ_API\Quiz\ValueObjects\AllowedDelay
      arguments:
        $value: 40

    quiz_year:
      class: \VSV\GVQ_API\Question\ValueObjects\Year
      arguments:
        $value: 2018

    quiz_start_date:
      class: \DateTimeImmutable
      arguments:
        $time: '2018-10-18'
        $timezone: '@time_zone'

    sender_email_nl:
      class: VSV\GVQ_API\User\ValueObjects\Email
      arguments:
        $value: '%sender_email_nl%'

    sender_name_nl:
      class: VSV\GVQ_API\Common\ValueObjects\NotEmptyString
      arguments:
        $value: '%sender_name_nl%'

    language_nl:
      class: VSV\GVQ_API\Common\ValueObjects\Language
      arguments:
        $value: 'nl'

    sender_nl:
      class: VSV\GVQ_API\Mail\Models\Sender
      arguments:
       $email: '@sender_email_nl'
       $name: '@sender_name_nl'
       $language: '@language_nl'

    sender_email_fr:
      class: VSV\GVQ_API\User\ValueObjects\Email
      arguments:
        $value: '%sender_email_fr%'

    sender_name_fr:
      class: VSV\GVQ_API\Common\ValueObjects\NotEmptyString
      arguments:
        $value: '%sender_name_fr%'

    language_fr:
      class: VSV\GVQ_API\Common\ValueObjects\Language
      arguments:
        $value: 'fr'

    sender_fr:
      class: VSV\GVQ_API\Mail\Models\Sender
      arguments:
       $email: '@sender_email_fr'
       $name: '@sender_name_fr'
       $language: '@language_fr'

    VSV\GVQ_API\Mail\Service\SwiftMailService:
      arguments:
        $senders: ['@sender_nl', '@sender_fr']

    partner_yaml_repository:
      class: VSV\GVQ_API\Partner\Repositories\PartnerYamlRepository
      arguments:
        $partnerFile: '%kernel.project_dir%/config/partners.yaml'

    redis_service:
      class: \Redis
      calls:
        - method: connect
          arguments:
            - 'redis'
            - 6379

    quiz_redis_repository:
      class: VSV\GVQ_API\Quiz\Repositories\QuizRedisRepository
      arguments:
        $redis: '@redis_service'

    started_quiz_redis_repository:
      class: VSV\GVQ_API\Statistics\Repositories\StartedQuizRedisRepository
      arguments:
        $redis: '@redis_service'

    finished_quiz_redis_repository:
      class: VSV\GVQ_API\Statistics\Repositories\FinishedQuizRedisRepository
      arguments:
        $redis: '@redis_service'

    question_result_redis_repository:
      class: VSV\GVQ_API\Quiz\Repositories\QuestionResultRedisRepository
      arguments:
        $redis: '@redis_service'

    unique_participant_redis_repository:
      class: VSV\GVQ_API\Statistics\Repositories\UniqueParticipantRedisRepository
      arguments:
        $redis: '@redis_service'

    question_result_projector:
      class: VSV\GVQ_API\Quiz\Projectors\QuestionResultProjector
      arguments:
        $questionResultRepository: '@question_result_redis_repository'

    started_quizzes_projector:
      class: VSV\GVQ_API\Statistics\Projectors\StartedQuizzesProjector
      arguments:
        $startedQuizRepository: '@started_quiz_redis_repository'

    finished_quizzes_projector:
      class: VSV\GVQ_API\Statistics\Projectors\FinishedQuizzesProjector
      arguments:
        $finishedQuizRepository: '@finished_quiz_redis_repository'
        $quizRepository: '@quiz_redis_repository'

    quiz_projector:
      class: VSV\GVQ_API\Quiz\Projectors\QuizProjector
      arguments:
        $quizRepository: '@quiz_redis_repository'

    unique_participant_projector:
      class: VSV\GVQ_API\Statistics\Projectors\UniqueParticipantProjector
      arguments:
        $uniqueParticipantRepository: '@unique_participant_redis_repository'
        $quizRepository: '@quiz_redis_repository'

    in_memory_event_store:
      class: Broadway\EventStore\InMemoryEventStore

    doctrine_event_store:
      class: VSV\GVQ_API\Quiz\EventStore\DoctrineEventStore

    simple_event_bus:
      class: Broadway\EventHandling\SimpleEventBus
      calls:
        - method: subscribe
          arguments:
            - '@started_quizzes_projector'
        - method: subscribe
          arguments:
            - '@question_result_projector'
        - method: subscribe
          arguments:
            - '@quiz_projector'
        - method: subscribe
          arguments:
          - '@finished_quizzes_projector'
        - method: subscribe
          arguments:
            - '@unique_participant_projector'

    quiz_aggregate_repository:
      class: VSV\GVQ_API\Quiz\Repositories\QuizAggregateRepository
      arguments:
        $eventStore: '@doctrine_event_store'
        $eventBus: '@simple_event_bus'

    quiz_composition_repository:
      class: VSV\GVQ_API\Quiz\Repositories\QuizCompositionYamlRepository
      arguments:
        $quizCompositionFile: '%kernel.project_dir%/config/quiz_composition.yaml'

    team_repository:
      class: VSV\GVQ_API\Team\Repositories\TeamYamlRepository
      arguments:
        $teamFile: '%kernel.project_dir%/config/teams.yaml'

    quiz_service:
      class: VSV\GVQ_API\Quiz\Service\QuizService
      arguments:
        $uuidFactory: '@uuid_factory'
        $quizCompositionRepository: '@quiz_composition_repository'
        $year: '@quiz_year'
        $allowedDelay: '@quiz_delay'

    statistics_service:
      class: VSV\GVQ_API\Statistics\Service\StatisticsService
      arguments:
        $startedQuizRepository: '@started_quiz_redis_repository'
        $finishedQuizRepository: '@finished_quiz_redis_repository'
        $uniqueParticipantRepository: '@unique_participant_redis_repository'
        $partnerRepository: '@partner_yaml_repository'
        $year : '@quiz_year'

    ### CONTROLLERS ###
    VSV\GVQ_API\Account\Controllers\AccountController:
      arguments:
        $jsonEnricher: '@registration_json_enricher'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Account\Controllers\AccountViewController:
      arguments:
        $uuidFactory: '@uuid_factory'
        $quizStartDate: '@quiz_start_date'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Question\Controllers\CategoryController:
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Company\Controllers\CompanyController:
      arguments:
        $jsonEnricher: '@company_json_enricher'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Question\Controllers\QuestionController:
      arguments:
        $uuidFactory: '@uuid_factory'
        $jsonEnricher: '@question_json_enricher'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Company\Controllers\CompanyViewController:
      arguments:
        $uuidFactory: '@uuid_factory'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Question\Controllers\QuestionViewController:
      arguments:
        $uuidFactory: '@uuid_factory'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\User\Controllers\UserViewController:
      arguments:
        $uuidFactory: '@uuid_factory'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Image\Controllers\ImageController:
      arguments:
        $fileSystem: '@fly_system'
        $imageValidator: '@image_validator'
        $uuidFactory: '@uuid_factory'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Quiz\Controllers\QuizController:
      arguments:
        $quizService: '@quiz_service'
        $quizAggregateRepository: '@quiz_aggregate_repository'
        $partnerRepository: '@partner_yaml_repository'
        $teamRepository: '@team_repository'
        $questionResultRepository: '@question_result_redis_repository'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Quiz\Controllers\QuizViewController:
      arguments:
        $year: '@quiz_year'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Statistics\Controllers\StatisticsViewController:
      arguments:
        $statisticsService: '@statistics_service'
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Dashboard\Controllers\DashboardViewController:
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Report\Controllers\ReportViewController:
      tags: ['controller.service_arguments']

    VSV\GVQ_API\Document\Controllers\DocumentViewController:
      tags: ['controller.service_arguments']
